project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Ralph Scott"
    search: false
    left:
      - href: index.qmd
        text: Home
      - CV.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    page-layout: full
    search: false

editor: visual

